//! MoTeC-compatible CSV export.
//!
//! Header format based on [pyxrk-dev](https://github.com/mitchdetailed/pyxrk-dev).

use std::io::Write;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::record::{GraphicsRecord, PhysicsRecord};

/// Write full physics records to MoTeC-compatible CSV with proper header.
pub fn write_csv(
    w: &mut impl Write,
    records: &[PhysicsRecord],
    sample_rate_hz: u32,
) -> std::io::Result<()> {
    let dt = 1.0 / sample_rate_hz as f64;
    let duration_secs = records.len() as f64 * dt;

    // Channel names and units (must match row data)
    let (names, units): (Vec<&str>, Vec<&str>) = (
        vec![
            "Time",
            "packet_id",
            "gas",
            "brake",
            "clutch",
            "steer_angle",
            "gear",
            "rpm",
            "autoshifter_on",
            "ignition_on",
            "starter_engine_on",
            "is_engine_running",
            "speed_kmh",
            "velocity_x",
            "velocity_y",
            "velocity_z",
            "local_velocity_x",
            "local_velocity_y",
            "local_velocity_z",
            "local_angular_vel_x",
            "local_angular_vel_y",
            "local_angular_vel_z",
            "g_force_x",
            "g_force_y",
            "g_force_z",
            "heading",
            "pitch",
            "roll",
            "final_ff",
            "wheel_slip_FL",
            "wheel_slip_FR",
            "wheel_slip_RL",
            "wheel_slip_RR",
            "wheel_load_FL",
            "wheel_load_FR",
            "wheel_load_RL",
            "wheel_load_RR",
            "wheel_pressure_FL",
            "wheel_pressure_FR",
            "wheel_pressure_RL",
            "wheel_pressure_RR",
            "wheel_angular_speed_FL",
            "wheel_angular_speed_FR",
            "wheel_angular_speed_RL",
            "wheel_angular_speed_RR",
            "tyre_wear_FL",
            "tyre_wear_FR",
            "tyre_wear_RL",
            "tyre_wear_RR",
            "tyre_dirty_level_FL",
            "tyre_dirty_level_FR",
            "tyre_dirty_level_RL",
            "tyre_dirty_level_RR",
            "tyre_core_temp_FL",
            "tyre_core_temp_FR",
            "tyre_core_temp_RL",
            "tyre_core_temp_RR",
            "camber_rad_FL",
            "camber_rad_FR",
            "camber_rad_RL",
            "camber_rad_RR",
            "suspension_travel_FL",
            "suspension_travel_FR",
            "suspension_travel_RL",
            "suspension_travel_RR",
            "brake_temp_FL",
            "brake_temp_FR",
            "brake_temp_RL",
            "brake_temp_RR",
            "brake_pressure_FL",
            "brake_pressure_FR",
            "brake_pressure_RL",
            "brake_pressure_RR",
            "suspension_damage_FL",
            "suspension_damage_FR",
            "suspension_damage_RL",
            "suspension_damage_RR",
            "slip_ratio_FL",
            "slip_ratio_FR",
            "slip_ratio_RL",
            "slip_ratio_RR",
            "slip_angle_FL",
            "slip_angle_FR",
            "slip_angle_RL",
            "slip_angle_RR",
            "pad_life_FL",
            "pad_life_FR",
            "pad_life_RL",
            "pad_life_RR",
            "disc_life_FL",
            "disc_life_FR",
            "disc_life_RL",
            "disc_life_RR",
            "front_brake_compound",
            "rear_brake_compound",
            "tyre_temp_i_FL",
            "tyre_temp_i_FR",
            "tyre_temp_i_RL",
            "tyre_temp_i_RR",
            "tyre_temp_m_FL",
            "tyre_temp_m_FR",
            "tyre_temp_m_RL",
            "tyre_temp_m_RR",
            "tyre_temp_o_FL",
            "tyre_temp_o_FR",
            "tyre_temp_o_RL",
            "tyre_temp_o_RR",
            "tyre_contact_point_FL_x",
            "tyre_contact_point_FL_y",
            "tyre_contact_point_FL_z",
            "tyre_contact_point_FR_x",
            "tyre_contact_point_FR_y",
            "tyre_contact_point_FR_z",
            "tyre_contact_point_RL_x",
            "tyre_contact_point_RL_y",
            "tyre_contact_point_RL_z",
            "tyre_contact_point_RR_x",
            "tyre_contact_point_RR_y",
            "tyre_contact_point_RR_z",
            "tyre_contact_normal_FL_x",
            "tyre_contact_normal_FL_y",
            "tyre_contact_normal_FL_z",
            "tyre_contact_normal_FR_x",
            "tyre_contact_normal_FR_y",
            "tyre_contact_normal_FR_z",
            "tyre_contact_normal_RL_x",
            "tyre_contact_normal_RL_y",
            "tyre_contact_normal_RL_z",
            "tyre_contact_normal_RR_x",
            "tyre_contact_normal_RR_y",
            "tyre_contact_normal_RR_z",
            "tyre_contact_heading_FL_x",
            "tyre_contact_heading_FL_y",
            "tyre_contact_heading_FL_z",
            "tyre_contact_heading_FR_x",
            "tyre_contact_heading_FR_y",
            "tyre_contact_heading_FR_z",
            "tyre_contact_heading_RL_x",
            "tyre_contact_heading_RL_y",
            "tyre_contact_heading_RL_z",
            "tyre_contact_heading_RR_x",
            "tyre_contact_heading_RR_y",
            "tyre_contact_heading_RR_z",
            "fuel",
            "tc",
            "abs",
            "pit_limiter_on",
            "turbo_boost",
            "air_temp",
            "road_temp",
            "water_temp",
            "car_damage_front",
            "car_damage_rear",
            "car_damage_left",
            "car_damage_right",
            "car_damage_center",
            "is_ai_controlled",
            "brake_bias",
            "tc_in_action",
            "abs_in_action",
            "drs",
            "cg_height",
            "number_of_tyres_out",
            "kers_charge",
            "kers_input",
            "ride_height_front",
            "ride_height_rear",
            "ballast",
            "air_density",
            "performance_meter",
            "engine_brake",
            "ers_recovery_level",
            "ers_power_level",
            "ers_heat_charging",
            "ers_is_charging",
            "kers_current_kj",
            "drs_available",
            "drs_enabled",
            "p2p_activation",
            "p2p_status",
            "current_max_rpm",
            "mz_FL",
            "mz_FR",
            "mz_RL",
            "mz_RR",
            "fz_FL",
            "fz_FR",
            "fz_RL",
            "fz_RR",
            "my_FL",
            "my_FR",
            "my_RL",
            "my_RR",
            "kerb_vibration",
            "slip_vibration",
            "g_vibration",
            "abs_vibration",
        ],
        vec![
            "s", "", "", "", "", "deg", "", "rpm", "", "", "", "", "km/h",
            "m/s", "m/s", "m/s", "m/s", "m/s", "m/s", "rad/s", "rad/s", "rad/s",
            "g", "g", "g", "rad", "rad", "rad", "",
            "", "", "", "", "N", "N", "N", "N",
            "psi", "psi", "psi", "psi",
            "rad/s", "rad/s", "rad/s", "rad/s",
            "", "", "", "", "", "", "", "",
            "C", "C", "C", "C",
            "rad", "rad", "rad", "rad",
            "mm", "mm", "mm", "mm",
            "C", "C", "C", "C",
            "bar", "bar", "bar", "bar",
            "", "", "", "",
            "", "", "", "",
            "deg", "deg", "deg", "deg",
            "%", "%", "%", "%",
            "%", "%", "%", "%",
            "", "",
            "C", "C", "C", "C",
            "C", "C", "C", "C",
            "C", "C", "C", "C",
            "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m",
            "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "bar", "C", "C", "C",
            "", "", "", "", "", "", "",
            "", "",
            "", "", "m", "", "", "mm", "mm", "kg", "kg/m3", "",
            "", "", "", "", "", "", "kJ", "", "", "", "",
            "", "Nm", "Nm", "Nm", "Nm", "N", "N", "N", "N", "Nm", "Nm", "Nm", "Nm",
            "", "", "", "",
        ],
    );

    let (log_date, log_time) = format_datetime();

    // MoTeC CSV header (pyxrk-dev structure)
    let header_rows: Vec<Vec<String>> = vec![
        vec!["Format".into(), "MoTeC CSV File".into(), "".into(), "".into(), "Workbook".into()],
        vec!["Venue".into(), "AC Rally".into(), "".into(), "".into(), "Worksheet".into()],
        vec!["Vehicle".into(), "Telemetry".into(), "".into(), "Vehicle Desc".into()],
        vec!["Driver".into(), "".into(), "".into(), "".into(), "Engine ID".into()],
        vec!["Device".into(), "ACR Recorder".into()],
        vec!["Comment".into(), "acr_recorder export".into(), "".into(), "".into(), "Session".into(), "Practice".into()],
        vec!["Log Date".into(), log_date.clone(), "".into(), "".into(), "Origin Time".into(), "0".into(), "s".into()],
        vec!["Log Time".into(), log_time.clone(), "".into(), "".into(), "Start Time".into(), "0".into(), "s".into()],
        vec!["Sample Rate".into(), sample_rate_hz.to_string(), "Hz".into(), "".into(), "End Time".into(), format!("{:.0}", duration_secs), "s".into()],
        vec!["Duration".into(), format!("{:.0}", duration_secs), "s".into(), "".into(), "Start Distance".into()],
        vec!["Range".into(), "entire outing".into(), "".into(), "".into(), "End Distance".into()],
        vec!["Beacon Markers".into(), "0".into()],
        vec![],
        vec![],
        names.iter().map(|s| (*s).to_string()).collect(),
        units.iter().map(|s| (*s).to_string()).collect(),
    ];

    for row in header_rows {
        writeln!(w, "{}", quote_row(&row))?;
    }

    // Data rows
    let b = |v: bool| if v { 1.0 } else { 0.0 };
    for (i, r) in records.iter().enumerate() {
        let time = i as f64 * dt;
        let row = vec![
            format!("{:.6}", time),
            format!("{}", r.packet_id),
            format!("{:.6}", r.gas),
            format!("{:.6}", r.brake),
            format!("{:.6}", r.clutch),
            format!("{:.4}", r.steer_angle),
            format!("{}", r.gear),
            format!("{}", r.rpm),
            format!("{:.0}", b(r.autoshifter_on)),
            format!("{:.0}", b(r.ignition_on)),
            format!("{:.0}", b(r.starter_engine_on)),
            format!("{:.0}", b(r.is_engine_running)),
            format!("{:.4}", r.speed_kmh),
            format!("{:.4}", r.velocity.x),
            format!("{:.4}", r.velocity.y),
            format!("{:.4}", r.velocity.z),
            format!("{:.4}", r.local_velocity.x),
            format!("{:.4}", r.local_velocity.y),
            format!("{:.4}", r.local_velocity.z),
            format!("{:.4}", r.local_angular_vel.x),
            format!("{:.4}", r.local_angular_vel.y),
            format!("{:.4}", r.local_angular_vel.z),
            format!("{:.4}", r.g_force.x),
            format!("{:.4}", r.g_force.y),
            format!("{:.4}", r.g_force.z),
            format!("{:.6}", r.heading),
            format!("{:.6}", r.pitch),
            format!("{:.6}", r.roll),
            format!("{:.4}", r.final_ff),
            format!("{:.4}", r.wheel_slip.front_left),
            format!("{:.4}", r.wheel_slip.front_right),
            format!("{:.4}", r.wheel_slip.rear_left),
            format!("{:.4}", r.wheel_slip.rear_right),
            format!("{:.2}", r.wheel_load.front_left),
            format!("{:.2}", r.wheel_load.front_right),
            format!("{:.2}", r.wheel_load.rear_left),
            format!("{:.2}", r.wheel_load.rear_right),
            format!("{:.4}", r.wheel_pressure.front_left),
            format!("{:.4}", r.wheel_pressure.front_right),
            format!("{:.4}", r.wheel_pressure.rear_left),
            format!("{:.4}", r.wheel_pressure.rear_right),
            format!("{:.4}", r.wheel_angular_speed.front_left),
            format!("{:.4}", r.wheel_angular_speed.front_right),
            format!("{:.4}", r.wheel_angular_speed.rear_left),
            format!("{:.4}", r.wheel_angular_speed.rear_right),
            format!("{:.4}", r.tyre_wear.front_left),
            format!("{:.4}", r.tyre_wear.front_right),
            format!("{:.4}", r.tyre_wear.rear_left),
            format!("{:.4}", r.tyre_wear.rear_right),
            format!("{:.4}", r.tyre_dirty_level.front_left),
            format!("{:.4}", r.tyre_dirty_level.front_right),
            format!("{:.4}", r.tyre_dirty_level.rear_left),
            format!("{:.4}", r.tyre_dirty_level.rear_right),
            format!("{:.2}", r.tyre_core_temp.front_left),
            format!("{:.2}", r.tyre_core_temp.front_right),
            format!("{:.2}", r.tyre_core_temp.rear_left),
            format!("{:.2}", r.tyre_core_temp.rear_right),
            format!("{:.6}", r.camber_rad.front_left),
            format!("{:.6}", r.camber_rad.front_right),
            format!("{:.6}", r.camber_rad.rear_left),
            format!("{:.6}", r.camber_rad.rear_right),
            format!("{:.4}", r.suspension_travel.front_left),
            format!("{:.4}", r.suspension_travel.front_right),
            format!("{:.4}", r.suspension_travel.rear_left),
            format!("{:.4}", r.suspension_travel.rear_right),
            format!("{:.2}", r.brake_temp.front_left),
            format!("{:.2}", r.brake_temp.front_right),
            format!("{:.2}", r.brake_temp.rear_left),
            format!("{:.2}", r.brake_temp.rear_right),
            format!("{:.4}", r.brake_pressure.front_left),
            format!("{:.4}", r.brake_pressure.front_right),
            format!("{:.4}", r.brake_pressure.rear_left),
            format!("{:.4}", r.brake_pressure.rear_right),
            format!("{:.4}", r.suspension_damage.front_left),
            format!("{:.4}", r.suspension_damage.front_right),
            format!("{:.4}", r.suspension_damage.rear_left),
            format!("{:.4}", r.suspension_damage.rear_right),
            format!("{:.4}", r.slip_ratio.front_left),
            format!("{:.4}", r.slip_ratio.front_right),
            format!("{:.4}", r.slip_ratio.rear_left),
            format!("{:.4}", r.slip_ratio.rear_right),
            format!("{:.4}", r.slip_angle.front_left),
            format!("{:.4}", r.slip_angle.front_right),
            format!("{:.4}", r.slip_angle.rear_left),
            format!("{:.4}", r.slip_angle.rear_right),
            format!("{:.2}", r.pad_life.front_left),
            format!("{:.2}", r.pad_life.front_right),
            format!("{:.2}", r.pad_life.rear_left),
            format!("{:.2}", r.pad_life.rear_right),
            format!("{:.2}", r.disc_life.front_left),
            format!("{:.2}", r.disc_life.front_right),
            format!("{:.2}", r.disc_life.rear_left),
            format!("{:.2}", r.disc_life.rear_right),
            format!("{}", r.front_brake_compound),
            format!("{}", r.rear_brake_compound),
            format!("{:.2}", r.tyre_temp_i.front_left),
            format!("{:.2}", r.tyre_temp_i.front_right),
            format!("{:.2}", r.tyre_temp_i.rear_left),
            format!("{:.2}", r.tyre_temp_i.rear_right),
            format!("{:.2}", r.tyre_temp_m.front_left),
            format!("{:.2}", r.tyre_temp_m.front_right),
            format!("{:.2}", r.tyre_temp_m.rear_left),
            format!("{:.2}", r.tyre_temp_m.rear_right),
            format!("{:.2}", r.tyre_temp_o.front_left),
            format!("{:.2}", r.tyre_temp_o.front_right),
            format!("{:.2}", r.tyre_temp_o.rear_left),
            format!("{:.2}", r.tyre_temp_o.rear_right),
            format!("{:.4}", r.tyre_contact_point.front_left.x),
            format!("{:.4}", r.tyre_contact_point.front_left.y),
            format!("{:.4}", r.tyre_contact_point.front_left.z),
            format!("{:.4}", r.tyre_contact_point.front_right.x),
            format!("{:.4}", r.tyre_contact_point.front_right.y),
            format!("{:.4}", r.tyre_contact_point.front_right.z),
            format!("{:.4}", r.tyre_contact_point.rear_left.x),
            format!("{:.4}", r.tyre_contact_point.rear_left.y),
            format!("{:.4}", r.tyre_contact_point.rear_left.z),
            format!("{:.4}", r.tyre_contact_point.rear_right.x),
            format!("{:.4}", r.tyre_contact_point.rear_right.y),
            format!("{:.4}", r.tyre_contact_point.rear_right.z),
            format!("{:.4}", r.tyre_contact_normal.front_left.x),
            format!("{:.4}", r.tyre_contact_normal.front_left.y),
            format!("{:.4}", r.tyre_contact_normal.front_left.z),
            format!("{:.4}", r.tyre_contact_normal.front_right.x),
            format!("{:.4}", r.tyre_contact_normal.front_right.y),
            format!("{:.4}", r.tyre_contact_normal.front_right.z),
            format!("{:.4}", r.tyre_contact_normal.rear_left.x),
            format!("{:.4}", r.tyre_contact_normal.rear_left.y),
            format!("{:.4}", r.tyre_contact_normal.rear_left.z),
            format!("{:.4}", r.tyre_contact_normal.rear_right.x),
            format!("{:.4}", r.tyre_contact_normal.rear_right.y),
            format!("{:.4}", r.tyre_contact_normal.rear_right.z),
            format!("{:.4}", r.tyre_contact_heading.front_left.x),
            format!("{:.4}", r.tyre_contact_heading.front_left.y),
            format!("{:.4}", r.tyre_contact_heading.front_left.z),
            format!("{:.4}", r.tyre_contact_heading.front_right.x),
            format!("{:.4}", r.tyre_contact_heading.front_right.y),
            format!("{:.4}", r.tyre_contact_heading.front_right.z),
            format!("{:.4}", r.tyre_contact_heading.rear_left.x),
            format!("{:.4}", r.tyre_contact_heading.rear_left.y),
            format!("{:.4}", r.tyre_contact_heading.rear_left.z),
            format!("{:.4}", r.tyre_contact_heading.rear_right.x),
            format!("{:.4}", r.tyre_contact_heading.rear_right.y),
            format!("{:.4}", r.tyre_contact_heading.rear_right.z),
            format!("{:.4}", r.fuel),
            format!("{:.4}", r.tc),
            format!("{:.4}", r.abs),
            format!("{:.0}", b(r.pit_limiter_on)),
            format!("{:.4}", r.turbo_boost),
            format!("{:.2}", r.air_temp),
            format!("{:.2}", r.road_temp),
            format!("{:.2}", r.water_temp),
            format!("{:.4}", r.car_damage.front),
            format!("{:.4}", r.car_damage.rear),
            format!("{:.4}", r.car_damage.left),
            format!("{:.4}", r.car_damage.right),
            format!("{:.4}", r.car_damage.center),
            format!("{:.0}", b(r.is_ai_controlled)),
            format!("{:.4}", r.brake_bias),
            format!("{:.0}", b(r.tc_in_action)),
            format!("{:.0}", b(r.abs_in_action)),
            format!("{}", r.drs),
            format!("{:.4}", r.cg_height),
            format!("{}", r.number_of_tyres_out),
            format!("{:.4}", r.kers_charge),
            format!("{:.4}", r.kers_input),
            format!("{:.4}", r.ride_height_front),
            format!("{:.4}", r.ride_height_rear),
            format!("{:.4}", r.ballast),
            format!("{:.6}", r.air_density),
            format!("{:.4}", r.performance_meter),
            format!("{}", r.engine_brake),
            format!("{}", r.ers_recovery_level),
            format!("{}", r.ers_power_level),
            format!("{}", r.ers_heat_charging),
            format!("{}", r.ers_is_charging),
            format!("{:.4}", r.kers_current_kj),
            format!("{}", r.drs_available),
            format!("{}", r.drs_enabled),
            format!("{}", r.p2p_activation),
            format!("{}", r.p2p_status),
            format!("{}", r.current_max_rpm),
            format!("{:.4}", r.mz.front_left),
            format!("{:.4}", r.mz.front_right),
            format!("{:.4}", r.mz.rear_left),
            format!("{:.4}", r.mz.rear_right),
            format!("{:.4}", r.fz.front_left),
            format!("{:.4}", r.fz.front_right),
            format!("{:.4}", r.fz.rear_left),
            format!("{:.4}", r.fz.rear_right),
            format!("{:.4}", r.my.front_left),
            format!("{:.4}", r.my.front_right),
            format!("{:.4}", r.my.rear_left),
            format!("{:.4}", r.my.rear_right),
            format!("{:.4}", r.kerb_vibration),
            format!("{:.4}", r.slip_vibration),
            format!("{:.4}", r.g_vibration),
            format!("{:.4}", r.abs_vibration),
        ];
        writeln!(w, "{}", quote_row(&row))?;
    }

    Ok(())
}

fn quote_row(row: &[String]) -> String {
    row.iter().map(|s| format!("\"{}\"", s)).collect::<Vec<_>>().join(",")
}

fn format_datetime() -> (String, String) {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let days = secs / 86400;
    let (y, m, d) = days_to_ymd(days);
    let h = (secs / 3600) % 24;
    let min = (secs / 60) % 60;
    let s = secs % 60;
    let date = format!("{:02}/{:02}/{:04}", d, m, y);
    let time = format!("{:02}:{:02}:{:02}", h, min, s);
    (date, time)
}

fn days_to_ymd(days: u64) -> (u32, u32, u32) {
    const EPOCH: i64 = 719163;
    let j = days as i64 + EPOCH;
    let a = (4 * j + 3) / 146097;
    let b = j - (146097 * a) / 4;
    let c = (4 * b + 3) / 1461;
    let d = b - (1461 * c) / 4;
    let e = (5 * d + 2) / 153;
    let day = (d - (153 * e + 2) / 5) as u32 + 1;
    let month = ((e + 2) % 12) as u32 + 1;
    let year = (100 * a + c) as u32;
    (year, month, day)
}

/// Write graphics records to CSV.
pub fn write_graphics_csv(
    w: &mut impl Write,
    records: &[GraphicsRecord],
    sample_rate_hz: u32,
) -> std::io::Result<()> {
    let dt = 1.0 / sample_rate_hz as f64;
    let duration_secs = records.len() as f64 * dt;
    
    let (date, time) = format_datetime();
    
    let names = vec![
        "Time", "packet_id", "status", "session_type", "session_index",
        "current_time_str", "last_time_str", "best_time_str", "last_sector_time_str",
        "completed_lap", "position",
        "current_time", "last_time", "best_time", "last_sector_time", "number_of_laps",
        "delta_lap_time_str", "estimated_lap_time_str",
        "delta_lap_time", "estimated_lap_time",
        "is_delta_positive", "is_valid_lap",
        "fuel_estimated_laps", "distance_traveled", "normalized_car_position",
        "session_time_left", "current_sector_index",
        "is_in_pit", "is_in_pit_lane", "ideal_line_on",
        "mandatory_pit_done", "missing_mandatory_pits",
        "penalty_time", "penalty", "flag",
        "player_car_id", "active_cars",
        "car_coordinates_x", "car_coordinates_y", "car_coordinates_z",
        "wind_speed", "wind_direction",
        "rain_intensity", "rain_intensity_in_10min", "rain_intensity_in_30min",
        "track_grip_status", "track_status", "clock",
        "tc_level", "tc_cut_level", "engine_map", "abs_level",
        "wiper_stage", "driver_stint_total_time_left", "driver_stint_time_left",
        "rain_tyres",
        "rain_light", "flashing_light", "light_stage",
        "direction_light_left", "direction_light_right",
        "tyre_compound", "is_setup_menu_visible",
        "main_display_index", "secondary_display_index",
        "fuel_per_lap", "used_fuel", "exhaust_temp",
        "gap_ahead", "gap_behind",
        "global_yellow", "global_yellow_s1", "global_yellow_s2", "global_yellow_s3",
        "global_white", "global_green", "global_chequered", "global_red",
        "mfd_tyre_set", "mfd_fuel_to_add",
        "mfd_tyre_pressure_FL", "mfd_tyre_pressure_FR", "mfd_tyre_pressure_RL", "mfd_tyre_pressure_RR",
        "current_tyre_set", "strategy_tyre_set",
    ];
    
    let units = vec![
        "s", "", "", "", "",
        "", "", "", "",
        "", "",
        "ms", "ms", "ms", "ms", "",
        "", "",
        "ms", "ms",
        "", "",
        "laps", "m", "",
        "s", "",
        "", "", "",
        "", "",
        "s", "", "",
        "", "",
        "m", "m", "m",
        "m/s", "deg",
        "", "", "",
        "", "", "s",
        "", "", "", "",
        "", "s", "s",
        "",
        "", "", "",
        "", "",
        "", "",
        "", "",
        "L/lap", "L", "C",
        "ms", "ms",
        "", "", "", "",
        "", "", "", "",
        "", "L",
        "psi", "psi", "psi", "psi",
        "", "",
    ];
    
    writeln!(w, "Format,6")?;
    writeln!(w, "Venue,ACC/AC Rally")?;
    writeln!(w, "Vehicle,Graphics Data")?;
    writeln!(w, "DateTime,{} {}", date, time)?;
    writeln!(w, "Event,Graphics Recording")?;
    writeln!(w, "Session,Graphics")?;
    writeln!(w, "Comment,Graphics data at ~{} Hz", sample_rate_hz)?;
    writeln!(w, "Duration,{:.3}", duration_secs)?;
    writeln!(w, "Range,0,{:.3}", duration_secs)?;
    writeln!(w, "Interval,{:.6}", dt)?;
    
    writeln!(w, "{}", quote_row(&names.iter().map(|s| s.to_string()).collect::<Vec<_>>()))?;
    writeln!(w, "{}", quote_row(&units.iter().map(|s| s.to_string()).collect::<Vec<_>>()))?;
    
    let b = |x: bool| if x { 1 } else { 0 };
    
    for (i, r) in records.iter().enumerate() {
        let time_offset = i as f64 * dt;
        let row = vec![
            format!("{:.6}", time_offset),
            format!("{}", r.packet_id),
            format!("{}", r.status),
            format!("{}", r.session_type),
            format!("{}", r.session_index),
            r.current_time_str.clone(),
            r.last_time_str.clone(),
            r.best_time_str.clone(),
            r.last_sector_time_str.clone(),
            format!("{}", r.completed_lap),
            format!("{}", r.position),
            format!("{}", r.current_time),
            format!("{}", r.last_time),
            format!("{}", r.best_time),
            format!("{}", r.last_sector_time),
            format!("{}", r.number_of_laps),
            r.delta_lap_time_str.clone(),
            r.estimated_lap_time_str.clone(),
            format!("{}", r.delta_lap_time),
            format!("{}", r.estimated_lap_time),
            format!("{}", b(r.is_delta_positive)),
            format!("{}", b(r.is_valid_lap)),
            format!("{:.4}", r.fuel_estimated_laps),
            format!("{:.4}", r.distance_traveled),
            format!("{:.6}", r.normalized_car_position),
            format!("{:.3}", r.session_time_left),
            format!("{}", r.current_sector_index),
            format!("{}", b(r.is_in_pit)),
            format!("{}", b(r.is_in_pit_lane)),
            format!("{}", b(r.ideal_line_on)),
            format!("{}", b(r.mandatory_pit_done)),
            format!("{}", r.missing_mandatory_pits),
            format!("{:.3}", r.penalty_time),
            format!("{}", r.penalty),
            format!("{}", r.flag),
            format!("{}", r.player_car_id),
            format!("{}", r.active_cars),
            format!("{:.4}", r.car_coordinates_x),
            format!("{:.4}", r.car_coordinates_y),
            format!("{:.4}", r.car_coordinates_z),
            format!("{:.4}", r.wind_speed),
            format!("{:.4}", r.wind_direction),
            format!("{}", r.rain_intensity),
            format!("{}", r.rain_intensity_in_10min),
            format!("{}", r.rain_intensity_in_30min),
            format!("{}", r.track_grip_status),
            r.track_status.clone(),
            format!("{:.3}", r.clock),
            format!("{}", r.tc_level),
            format!("{}", r.tc_cut_level),
            format!("{}", r.engine_map),
            format!("{}", r.abs_level),
            format!("{}", r.wiper_stage),
            format!("{}", r.driver_stint_total_time_left),
            format!("{}", r.driver_stint_time_left),
            format!("{}", b(r.rain_tyres)),
            format!("{}", b(r.rain_light)),
            format!("{}", b(r.flashing_light)),
            format!("{}", r.light_stage),
            format!("{}", b(r.direction_light_left)),
            format!("{}", b(r.direction_light_right)),
            r.tyre_compound.clone(),
            format!("{}", b(r.is_setup_menu_visible)),
            format!("{}", r.main_display_index),
            format!("{}", r.secondary_display_index),
            format!("{:.4}", r.fuel_per_lap),
            format!("{:.4}", r.used_fuel),
            format!("{:.4}", r.exhaust_temp),
            format!("{}", r.gap_ahead),
            format!("{}", r.gap_behind),
            format!("{}", b(r.global_yellow)),
            format!("{}", b(r.global_yellow_s1)),
            format!("{}", b(r.global_yellow_s2)),
            format!("{}", b(r.global_yellow_s3)),
            format!("{}", b(r.global_white)),
            format!("{}", b(r.global_green)),
            format!("{}", b(r.global_chequered)),
            format!("{}", b(r.global_red)),
            format!("{}", r.mfd_tyre_set),
            format!("{:.2}", r.mfd_fuel_to_add),
            format!("{:.2}", r.mfd_tyre_pressure_fl),
            format!("{:.2}", r.mfd_tyre_pressure_fr),
            format!("{:.2}", r.mfd_tyre_pressure_rl),
            format!("{:.2}", r.mfd_tyre_pressure_rr),
            format!("{}", r.current_tyre_set),
            format!("{}", r.strategy_tyre_set),
        ];
        writeln!(w, "{}", quote_row(&row))?;
    }
    
    Ok(())
}
