{
 "title": "AC Rally compare",
 "time": { "from": "2001-09-09T01:46:49.721Z", "to": "2001-09-09T01:47:10.061Z" },
 "templating": {
  "list": [
   {
    "name": "id_a",
    "label": "recording_id_a",
    "query": "SELECT id FROM recordings ORDER BY id ASC"
   },
   {
    "name": "id_b",
    "label": "recording_id_b",
    "query": "select id from recordings where not(id= $id_a)"
   },
   { "name": "offset_a", "label": "offset_a [seconds]" },
   { "name": "offset_b", "label": "offset_b [seconds]" },
   {
    "name": "recording_min_ts",
    "query": "SELECT MIN(ts) FROM (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL), 0)) * 1000 AS ts FROM physics WHERE recording_id = $id_a UNION ALL SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL), 0)) * 1000 AS ts FROM physics WHERE recording_id = $id_b)"
   },
   {
    "name": "recording_max_ts",
    "query": "SELECT MAX(ts) FROM (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL), 0)) * 1000 AS ts FROM physics WHERE recording_id = $id_a UNION ALL SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL), 0)) * 1000 AS ts FROM physics WHERE recording_id = $id_b)"
   }
  ]
 },
 "panels": [
  {
   "title": "Synchronisation info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "select recording_id, id, time_offset_sec, 1000000000+time_offset_sec as time, text, tag from annotations where ((recording_id = $id_a) or (recording_id = $id_b)) and tag = 'sync_speed_gt_0'\n",
     "rawQueryText": "select recording_id, id, time_offset_sec, 1000000000+time_offset_sec as time, text, tag from annotations where ((recording_id = $id_a) or (recording_id = $id_b)) and tag = 'sync_speed_gt_0'\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select recording_id, id, time_offset_sec, 1000000000+time_offset_sec as time, text, tag from annotations where ((recording_id = $id_a) or (recording_id = $id_b)) and tag = 'sync_air_temp_gt_0'\n\n",
     "rawQueryText": "select recording_id, id, time_offset_sec, 1000000000+time_offset_sec as time, text, tag from annotations where ((recording_id = $id_a) or (recording_id = $id_b)) and tag = 'sync_air_temp_gt_0'\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Speed + RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, rpm, speed_kmh, gear FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, rpm, speed_kmh, gear FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0) ) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, rpm as rpm_b, speed_kmh as speed_kmh_b, gear as gear_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0) ) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, rpm as rpm_b, speed_kmh as speed_kmh_b, gear as gear_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Recordings overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT id as recording_id, s.car_model, source_file, duration_secs, sample_count from recordings join statics s on recordings.id = s.recording_id",
     "rawQueryText": "SELECT id as recording_id, s.car_model, source_file, duration_secs, sample_count from recordings join statics s on recordings.id = s.recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000337724 - 999999914728) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR,brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (23) AND (1000000000 + time_offset) * 1000 BETWEEN 999999914728 AND 1000000337724) \nSELECT time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR, brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, tyre_core_temp_FL, tyre_core_temp_FR, tyre_core_temp_RL, tyre_core_temp_RR, brake_temp_FL, brake_temp_FR, brake_temp_RL, brake_temp_RR, air_temp, road_temp, water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, tyre_core_temp_FL, tyre_core_temp_FR, tyre_core_temp_RL, tyre_core_temp_RR, brake_temp_FL, brake_temp_FR, brake_temp_RL, brake_temp_RR, air_temp, road_temp, water_temp FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, tyre_core_temp_FL, tyre_core_temp_FR, tyre_core_temp_RL, tyre_core_temp_RR, brake_temp_FL, brake_temp_FR, brake_temp_RL, brake_temp_RR, air_temp, road_temp, water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, tyre_core_temp_FL AS tyre_core_temp_FL_b, tyre_core_temp_FR AS tyre_core_temp_FR_b, tyre_core_temp_RL AS tyre_core_temp_RL_b, tyre_core_temp_RR AS tyre_core_temp_RR_b, brake_temp_FL AS brake_temp_FL_b, brake_temp_FR AS brake_temp_FR_b, brake_temp_RL AS brake_temp_RL_b, brake_temp_RR AS brake_temp_RR_b, air_temp AS air_temp_b, road_temp AS road_temp_b, water_temp AS water_temp_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, tyre_core_temp_FL, tyre_core_temp_FR, tyre_core_temp_RL, tyre_core_temp_RR, brake_temp_FL, brake_temp_FR, brake_temp_RL, brake_temp_RR, air_temp, road_temp, water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, tyre_core_temp_FL AS tyre_core_temp_FL_b, tyre_core_temp_FR AS tyre_core_temp_FR_b, tyre_core_temp_RL AS tyre_core_temp_RL_b, tyre_core_temp_RR AS tyre_core_temp_RR_b, brake_temp_FL AS brake_temp_FL_b, brake_temp_FR AS brake_temp_FR_b, brake_temp_RL AS brake_temp_RL_b, brake_temp_RR AS brake_temp_RR_b, air_temp AS air_temp_b, road_temp AS road_temp_b, water_temp AS water_temp_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "G-Scope",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000034482 - 1000000030543) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST(13.2 AS REAL),0.0)) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (52) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset + COALESCE(CAST(13.2 AS REAL),0.0)) * 1000 BETWEEN 1000000030543 AND 1000000034482) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000034482 - 1000000030543) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST(17.6 AS REAL),0.0)) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (55) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset + COALESCE(CAST(17.6 AS REAL),0.0)) * 1000 BETWEEN 1000000030543 AND 1000000034482) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Route",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 7, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, heading, car_pos_x, car_pos_y, car_pos_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, heading, car_pos_x, car_pos_y, car_pos_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, heading heading_b, car_pos_x b_pos_x, car_pos_y b_pos_y, car_pos_z b_pos_z, speed_kmh b_speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, heading heading_b, car_pos_x b_pos_x, car_pos_y b_pos_y, car_pos_z b_pos_z, speed_kmh b_speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Angles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y, tyre_contact_normal_FR_y, tyre_contact_normal_RR_y, tyre_contact_normal_RL_y, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($id_a) AND (1000000000 + p.time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle, car_roll_angle, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR, 57.3*acos(tyre_contact_normal_FL_y) as camber_FL, 57.3*acos(tyre_contact_normal_RR_y) as camber_RR, 57.3*acos(tyre_contact_normal_RL_y) as camber_RL FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y, tyre_contact_normal_FR_y, tyre_contact_normal_RR_y, tyre_contact_normal_RL_y, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($id_a) AND (1000000000 + p.time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle, car_roll_angle, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR, 57.3*acos(tyre_contact_normal_FL_y) as camber_FL, 57.3*acos(tyre_contact_normal_RR_y) as camber_RR, 57.3*acos(tyre_contact_normal_RL_y) as camber_RL FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y, tyre_contact_normal_FR_y, tyre_contact_normal_RR_y, tyre_contact_normal_RL_y, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($id_b) AND (1000000000 + p.time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle AS car_pitch_angle_b, car_roll_angle AS car_roll_angle_b, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR_b, 57.3*acos(tyre_contact_normal_FL_y) as camber_FL_b, 57.3*acos(tyre_contact_normal_RR_y) as camber_RR_b, 57.3*acos(tyre_contact_normal_RL_y) as camber_RL_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y, tyre_contact_normal_FR_y, tyre_contact_normal_RR_y, tyre_contact_normal_RL_y, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($id_b) AND (1000000000 + p.time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle AS car_pitch_angle_b, car_roll_angle AS car_roll_angle_b, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR_b, 57.3*acos(tyre_contact_normal_FL_y) as camber_FL_b, 57.3*acos(tyre_contact_normal_RR_y) as camber_RR_b, 57.3*acos(tyre_contact_normal_RL_y) as camber_RL_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, steer_angle, gas, brake, clutch FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, steer_angle, gas, brake, clutch FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, steer_angle AS steer_angle_b, gas AS gas_b, brake AS brake_b, clutch AS clutch_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, steer_angle AS steer_angle_b, gas AS gas_b, brake AS brake_b, clutch AS clutch_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Wheel data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, wheel_load_fl AS wheel_load_fl_b, wheel_load_fr AS wheel_load_fr_b, wheel_load_rl AS wheel_load_rl_b, wheel_load_rr AS wheel_load_rr_b, wheel_slip_fl AS wheel_slip_fl_b, wheel_slip_fr AS wheel_slip_fr_b, wheel_slip_rl AS wheel_slip_rl_b, wheel_slip_rr AS wheel_slip_rr_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, wheel_load_fl AS wheel_load_fl_b, wheel_load_fr AS wheel_load_fr_b, wheel_load_rl AS wheel_load_rl_b, wheel_load_rr AS wheel_load_rr_b, wheel_slip_fl AS wheel_slip_fl_b, wheel_slip_fr AS wheel_slip_fr_b, wheel_slip_rl AS wheel_slip_rl_b, wheel_slip_rr AS wheel_slip_rr_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "accelerations and forces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, speed_kmh, heading, g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, TurningFl, TurningFR, TurningRL, TurningRR FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, speed_kmh, heading, g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, TurningFl, TurningFR, TurningRL, TurningRR FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, speed_kmh AS speed_kmh_b, heading AS heading_b, g_lateral AS g_lateral_b, g_longit AS g_longit_b, wheelForceFL AS wheelForceFL_b, wheelForceFR AS wheelForceFR_b, wheelForceRL AS wheelForceRL_b, wheelForceRR AS wheelForceRR_b, TurningFl AS TurningFl_b, TurningFR AS TurningFR_b, TurningRL AS TurningRL_b, TurningRR AS TurningRR_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, speed_kmh AS speed_kmh_b, heading AS heading_b, g_lateral AS g_lateral_b, g_longit AS g_longit_b, wheelForceFL AS wheelForceFL_b, wheelForceFR AS wheelForceFR_b, wheelForceRL AS wheelForceRL_b, wheelForceRR AS wheelForceRR_b, TurningFl AS TurningFl_b, TurningFR AS TurningFR_b, TurningRL AS TurningRL_b, TurningRR AS TurningRR_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Suspension data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, suspension_travel_fl AS suspension_travel_fl_b, suspension_travel_fr AS suspension_travel_fr_b, suspension_travel_rl AS suspension_travel_rl_b, suspension_travel_rr AS suspension_travel_rr_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, suspension_travel_fl AS suspension_travel_fl_b, suspension_travel_fr AS suspension_travel_fr_b, suspension_travel_rl AS suspension_travel_rl_b, suspension_travel_rr AS suspension_travel_rr_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Static",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "queryText": "SELECT s.car_model, r.*  from recordings as r join statics as s on r.id = s.recording_id where r.id in ($id_a)\r\n",
     "rawQueryText": "SELECT s.car_model, r.*  from recordings as r join statics as s on r.id = s.recording_id where r.id in ($id_a)\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Driving aids",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, abs, tc, abs_in_action, tc_in_action, abs_vibration FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_a) AND (1000000000 + time_offset + COALESCE(CAST($offset_a AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, abs, tc, abs_in_action, tc_in_action, abs_vibration FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, abs AS abs_b, tc AS tc_b, abs_in_action AS abs_in_action_b, tc_in_action AS tc_in_action_b, abs_vibration AS abs_vibration_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($id_b) AND (1000000000 + time_offset + COALESCE(CAST($offset_b AS REAL),0.0)) * 1000 BETWEEN $__from AND $__to) SELECT time, abs AS abs_b, tc AS tc_b, abs_in_action AS abs_in_action_b, tc_in_action AS tc_in_action_b, abs_vibration AS abs_vibration_b FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}