{
 "title": "AC Rally full",
 "time": { "from": "2026-02-20T09:38:17.787Z", "to": "2026-02-20T21:38:17.787Z" },
 "templating": {
  "list": [
   { "name": "recording_id", "query": "SELECT id FROM recordings" },
   {
    "name": "recording_min_ts",
    "query": "SELECT MIN((1000000000 + time_offset) * 1000) FROM physics WHERE recording_id = $recording_id"
   },
   {
    "name": "recording_max_ts",
    "query": "SELECT MAX((1000000000 + time_offset) * 1000) FROM physics WHERE recording_id = $recording_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Driver Annotations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT id, time_offset_sec + 1000000000 as time, time_offset_sec, text, tag from annotations where recording_id = $recording_id and not(tag = 'sync_speed_gt_0' or tag = 'sync_air_temp_gt_0')",
     "rawQueryText": "SELECT id, time_offset_sec + 1000000000 as time, time_offset_sec, text, tag from annotations where recording_id = $recording_id and not(tag = 'sync_speed_gt_0' or tag = 'sync_air_temp_gt_0')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Speed + RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1031549400000 - 1031513400000) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (48) AND (1000000000 + time_offset) * 1000 BETWEEN 1031513400000 AND 1031549400000) SELECT time, rpm, speed_kmh, gear FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, rpm, speed_kmh, gear FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT * from physics where recording_id = $recording_id limit 1000",
     "rawQueryText": "SELECT * from physics where recording_id = $recording_id limit 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Driving Aids",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT max(tc), max(abs) from physics where recording_id = $recording_id",
     "rawQueryText": "SELECT max(tc), max(abs) from physics where recording_id = $recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000337724 - 999999914728) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR,brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (23) AND (1000000000 + time_offset) * 1000 BETWEEN 999999914728 AND 1000000337724) \nSELECT time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR, brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR,brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \nSELECT time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR, brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Recordings overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT id as recording_id, s.car_model, source_file, duration_secs, sample_count from recordings join statics s on recordings.id = s.recording_id",
     "rawQueryText": "SELECT id as recording_id, s.car_model, source_file, duration_secs, sample_count from recordings join statics s on recordings.id = s.recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "G-Scope",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Route",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 7, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, heading, car_pos_x, car_pos_y, car_pos_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, heading, car_pos_x, car_pos_y, car_pos_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Angles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y , tyre_contact_normal_FR_y ,tyre_contact_normal_RR_y ,tyre_contact_normal_RL_y ,ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle, car_roll_angle, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR,57.3*acos(tyre_contact_normal_FL_y) as camber_FL ,57.3*acos(tyre_contact_normal_RR_y) as camber_RR ,57.3*acos(tyre_contact_normal_RL_y) as camber_RL FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y , tyre_contact_normal_FR_y ,tyre_contact_normal_RR_y ,tyre_contact_normal_RL_y ,ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle, car_roll_angle, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR,57.3*acos(tyre_contact_normal_FL_y) as camber_FL ,57.3*acos(tyre_contact_normal_RR_y) as camber_RR ,57.3*acos(tyre_contact_normal_RL_y) as camber_RL FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000169428 - 999999874516) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (55) AND (1000000000 + time_offset) * 1000 BETWEEN 999999874516 AND 1000000169428) SELECT time, steer_angle, gas, brake, clutch FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, steer_angle, gas, brake, clutch FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Wheel data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "queryText": "WITH \r\nstep AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \r\ndata AS (SELECT (1000000000 + time_offset) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fr, slip_angle_fl, slip_angle_rr, slip_angle_rl,slip_ratio_fr, slip_ratio_fl, slip_ratio_rr, slip_ratio_rl, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\n\r\nSELECT time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fl, slip_angle_fr, slip_angle_rl, slip_angle_rr,slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr  FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH \r\nstep AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \r\ndata AS (SELECT (1000000000 + time_offset) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fr, slip_angle_fl, slip_angle_rr, slip_angle_rl,slip_ratio_fr, slip_ratio_fl, slip_ratio_rr, slip_ratio_rl, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\n\r\nSELECT time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fl, slip_angle_fr, slip_angle_rl, slip_angle_rr,slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr  FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "accelerations and forces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, speed_kmh, heading, g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, TurningFl, TurningFR, TurningRL, TurningRR FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, speed_kmh, heading, g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, TurningFl, TurningFR, TurningRL, TurningRR FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Suspension data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Static",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "queryText": "SELECT s.car_model, r.*  from recordings as r join statics as s on r.id = s.recording_id where r.id in ($recording_id)\r\n",
     "rawQueryText": "SELECT s.car_model, r.*  from recordings as r join statics as s on r.id = s.recording_id where r.id in ($recording_id)\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Driving aids",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, abs, tc, abs_in_action, tc_in_action, abs_vibration FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, abs, tc, abs_in_action, tc_in_action, abs_vibration FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}