{
 "title": "AC Rally full",
 "time": { "from": "2001-09-09T01:47:26.962Z", "to": "2001-09-09T01:50:23.362Z" },
 "templating": {
  "list": [
   { "name": "recording_id", "query": "SELECT id FROM recordings" },
   {
    "name": "recording_min_ts",
    "query": "SELECT MIN((1000000000 + time_offset) * 1000) FROM physics WHERE recording_id = $recording_id"
   },
   {
    "name": "recording_max_ts",
    "query": "SELECT MAX((1000000000 + time_offset) * 1000) FROM physics WHERE recording_id = $recording_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Title and notes",
     "type": "table",
     "gridPos": { "h": 4, "w": 20, "x": 0, "y": 1 },
     "targets": [
      {
       "queryText": "SELECT r.*, GROUP_CONCAT(distinct t.tag_name) as tags, s.car_model as car_model, max(g.distance_traveled) as maximum_distance_traveled\nFROM recordings r\nLEFT JOIN acr_tag_lookup l ON r.id = l.recording_id\nLEFT JOIN acr_telemetry_tags t ON l.tag_id = t.id\nLEFT JOIN statics s on r.id = s.recording_id\nleft join graphics g on r.id = g.recording_id\nWHERE r.id = 5\nGROUP BY r.id",
       "rawQueryText": "SELECT r.*, GROUP_CONCAT(distinct t.tag_name) as tags, s.car_model as car_model, max(g.distance_traveled) as maximum_distance_traveled\nFROM recordings r\nLEFT JOIN acr_tag_lookup l ON r.id = l.recording_id\nLEFT JOIN acr_telemetry_tags t ON l.tag_id = t.id\nLEFT JOIN statics s on r.id = s.recording_id\nleft join graphics g on r.id = g.recording_id\nWHERE r.id = $recording_id\nGROUP BY r.id",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Route",
     "type": "geomap",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000247704 - 1000000009366) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (56) AND (1000000000 + time_offset) * 1000 BETWEEN 1000000009366 AND 1000000247704) SELECT time, heading, car_pos_x, car_pos_y, car_pos_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, heading*57.3 AS heading, (tyre_contact_point_fl_x + tyre_contact_point_fr_x + tyre_contact_point_rl_x + tyre_contact_point_rr_x) / 40000.0 AS car_pos_x, (tyre_contact_point_fl_y + tyre_contact_point_fr_y + tyre_contact_point_rl_y + tyre_contact_point_rr_y) / 4.0 AS car_pos_y, (tyre_contact_point_fl_z + tyre_contact_point_fr_z + tyre_contact_point_rl_z + tyre_contact_point_rr_z) / 40000.0 AS car_pos_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, heading, car_pos_x, car_pos_y, car_pos_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "G-Scope",
     "type": "xychart",
     "gridPos": { "h": 13, "w": 5, "x": 7, "y": 5 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, g_force_x, g_force_z, speed_kmh, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND abs(g_force_x) < 2 AND abs(g_force_z) < 2 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, g_force_x, g_force_z, speed_kmh FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Speed + RPM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, rpm, speed_kmh, gear FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, rpm, speed_kmh, gear-1 AS gear, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, rpm, speed_kmh, gear FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "SELECT * from physics where recording_id = 1 limit 1000",
       "rawQueryText": "SELECT * from physics where recording_id = $recording_id limit 1000",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Acceleration over Speed",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "queryText": "select speed_kmh,  -fz_FL - fz_FR - (fz_RL + fz_RR) as acc_gear1 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and  gas > 0.99 and gear = 2",
       "rawQueryText": "select speed_kmh,  -fz_FL - fz_FR - (fz_RL + fz_RR) as acc_gear1 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and  gas > 0.99 and gear = 2",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR) as acc_gear2 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.99 and gear = 3",
       "rawQueryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR) as acc_gear2 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.99 and gear = 3",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR) as acc_gear3 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.99 and gear = 4",
       "rawQueryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR) as acc_gear3 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.99 and gear = 4",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR)as acc_gear4 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.99 and gear = 5",
       "rawQueryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR)as acc_gear4 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.99 and gear = 5",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR)as acc_gear5 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.9 and gear = 6",
       "rawQueryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR)as acc_gear5 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.9 and gear = 6",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR)as acc_gear6 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.9 and gear = 7",
       "rawQueryText": "select speed_kmh, -fz_FL - fz_FR - (fz_RL + fz_RR)as acc_gear6 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and g_force_z > 0 and gas > 0.9 and gear = 7",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Driver Annotations",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "queryText": "SELECT id, time_offset_sec + 1000000000 as time, time_offset_sec, text, tag from annotations where recording_id = $recording_id and not(tag = 'sync_speed_gt_0' or tag = 'sync_air_temp_gt_0')",
       "rawQueryText": "SELECT id, time_offset_sec + 1000000000 as time, time_offset_sec, text, tag from annotations where recording_id = $recording_id and not(tag = 'sync_speed_gt_0' or tag = 'sync_air_temp_gt_0')",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "kelvin" } },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000122464 - 999999967584) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR,brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (109) AND (1000000000 + time_offset) * 1000 BETWEEN 999999967584 AND 1000000122464) \nSELECT time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR, brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR,brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \nSELECT time, tyre_core_temp_FL ,tyre_core_temp_FR ,tyre_core_temp_RL ,tyre_core_temp_RR, brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, air_temp ,road_temp ,water_temp FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Recordings overview",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "queryText": "SELECT id as recording_id, s.car_model, source_file, duration_secs, sample_count from recordings join statics s on recordings.id = s.recording_id",
       "rawQueryText": "SELECT id as recording_id, s.car_model, source_file, duration_secs, sample_count from recordings join statics s on recordings.id = s.recording_id",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Static",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "queryText": "SELECT s.car_model, r.*  from recordings as r join statics as s on r.id = s.recording_id where r.id in ($recording_id)\r\n",
       "rawQueryText": "SELECT s.car_model, r.*  from recordings as r join statics as s on r.id = s.recording_id where r.id in ($recording_id)\r\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Driving aids",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, abs, tc, abs_in_action, tc_in_action, abs_vibration FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, physics.abs, tc, abs_in_action, tc_in_action, abs_vibration, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, abs, tc, abs_in_action, tc_in_action, abs_vibration FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Angles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y , tyre_contact_normal_FR_y ,tyre_contact_normal_RR_y ,tyre_contact_normal_RL_y ,ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle, car_roll_angle, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR,57.3*acos(tyre_contact_normal_FL_y) as camber_FL ,57.3*acos(tyre_contact_normal_RR_y) as camber_RR ,57.3*acos(tyre_contact_normal_RL_y) as camber_RL FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + p.time_offset) AS time, pitch*57.3 AS car_pitch_angle, roll*57.3 AS car_roll_angle, tyre_contact_normal_FL_y , tyre_contact_normal_FR_y ,tyre_contact_normal_RR_y ,tyre_contact_normal_RL_y ,ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, car_pitch_angle, car_roll_angle, 57.3*acos(tyre_contact_normal_FR_y) as camber_FR,57.3*acos(tyre_contact_normal_FL_y) as camber_FL ,57.3*acos(tyre_contact_normal_RR_y) as camber_RR ,57.3*acos(tyre_contact_normal_RL_y) as camber_RL FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "New panel",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,-(my_fl +my_fr - my_rl- my_rr ) as oversteer, g_force_x as g_force_x, steer_angle, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id IN ($recording_id) and g_force_x > 0.2 and g_force_z between -0.1 and 0.1 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time, g_force_x,  oversteer, steer_angle\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,-(my_fl +my_fr - my_rl- my_rr ) as oversteer, g_force_x as g_force_x, steer_angle, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id IN ($recording_id) and g_force_x > 0.2 and g_force_z between -0.1 and 0.1 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time, g_force_x,  oversteer, steer_angle\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,(my_fl +my_fr - my_rl- my_rr ) as oversteer, -g_force_x as g_force_x, -steer_angle as steer_angle, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id IN ($recording_id) and g_force_x < -0.2 and g_force_z between -0.1 and 0.1 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time, g_force_x,  oversteer, steer_angle\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,(my_fl +my_fr - my_rl- my_rr ) as oversteer, -g_force_x as g_force_x, -steer_angle as steer_angle, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id IN ($recording_id) and g_force_x < -0.2 and g_force_z between -0.1 and 0.1 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time, g_force_x,  oversteer, steer_angle\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "accelerations and forces",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000084996 - 1000000000000) / 1000 / 5000 AS INTEGER)) AS s), data AS \r\n(SELECT (1000000000 + time_offset) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (63) AND (1000000000 + time_offset) * 1000 BETWEEN 1000000000000 AND 1000000084996) \r\nSELECT time, speed_kmh, heading, g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, TurningFl, TurningFR, TurningRL, TurningRR FROM \r\ndata, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS \r\n(SELECT (1000000000 + time_offset) AS time, speed_kmh, heading, g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, -\"mz_FL\" AS TurningFl, -\"mz_FR\" AS TurningFR, -\"mz_RL\" AS TurningRL, -mz_RR AS TurningRR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\nSELECT time, speed_kmh, heading, g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, TurningFl, TurningFR, TurningRL, TurningRR FROM \r\ndata, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Inputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000169428 - 999999874516) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (55) AND (1000000000 + time_offset) * 1000 BETWEEN 999999874516 AND 1000000169428) SELECT time, steer_angle, gas, brake, clutch FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, steer_angle, gas, brake, -clutch AS clutch, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, steer_angle, gas, brake, clutch FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Driving Aids",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "queryText": "SELECT max(tc), max(abs) from physics where recording_id = $recording_id",
     "rawQueryText": "SELECT max(tc), max(abs) from physics where recording_id = $recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Gearing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Speed per gear histogram",
     "type": "histogram",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "queryText": "select speed_kmh as speed_gear1 from physics where recording_id = 98 and (1000000000 + time_offset) * 1000 BETWEEN 1000000000000 AND 1000000146330 and gear = 2 and rpm < current_max_rpm",
       "rawQueryText": "select speed_kmh as speed_gear1 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and gear = 2 and rpm < current_max_rpm",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh as speed_gear2 from physics where recording_id = 98 and (1000000000 + time_offset) * 1000 BETWEEN 1000000000000 AND 1000000146330 and rpm < current_max_rpm  and gear = 3",
       "rawQueryText": "select speed_kmh as speed_gear2 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm  and gear = 3",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh as speed_gear3 from physics where recording_id = 98 and (1000000000 + time_offset) * 1000 BETWEEN 1000000000000 AND 1000000146330  and rpm < current_max_rpm and gear = 4",
       "rawQueryText": "select speed_kmh as speed_gear3 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and rpm < current_max_rpm and gear = 4",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh as speed_gear4 from physics where recording_id = 98 and (1000000000 + time_offset) * 1000 BETWEEN 1000000000000 AND 1000000146330 and rpm < current_max_rpm and gear = 5",
       "rawQueryText": "select speed_kmh as speed_gear4 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm and gear = 5",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh as speed_gear5 from physics where recording_id = 98 and (1000000000 + time_offset) * 1000 BETWEEN 1000000000000 AND 1000000146330 and rpm < current_max_rpm and gear = 6",
       "rawQueryText": "select speed_kmh as speed_gear5 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm and gear = 6",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select speed_kmh  as speed_gear6 from physics where recording_id = 98 and (1000000000 + time_offset) * 1000 BETWEEN 1000000000000 AND 1000000146330  and rpm < current_max_rpm and gear = 7",
       "rawQueryText": "select speed_kmh  as speed_gear6 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and rpm < current_max_rpm and gear = 7",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "RPM per gear histogram",
     "type": "histogram",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "queryText": "select rpm as speed_gear1 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and gear = 2 and rpm < current_max_rpm and gas > 0.3",
       "rawQueryText": "select rpm as speed_gear1 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and gear = 2 and rpm < current_max_rpm and gas > 0.3",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select rpm as speed_gear2 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm  and gear = 3  and gas > 0.3",
       "rawQueryText": "select rpm as speed_gear2 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm  and gear = 3  and gas > 0.3",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select rpm as speed_gear3 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and rpm < current_max_rpm and gear = 4  and gas > 0.3",
       "rawQueryText": "select rpm as speed_gear3 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and rpm < current_max_rpm and gear = 4  and gas > 0.3",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select rpm as speed_gear4 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm and gear = 5  and gas > 0.3",
       "rawQueryText": "select rpm as speed_gear4 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm and gear = 5  and gas > 0.3",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select rpm as speed_gear5 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm and gear = 6  and gas > 0.3",
       "rawQueryText": "select rpm as speed_gear5 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to and rpm < current_max_rpm and gear = 6  and gas > 0.3",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "select rpm as speed_gear6 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and rpm < current_max_rpm and gear = 7  and gas > 0.3",
       "rawQueryText": "select rpm as speed_gear6 from physics where recording_id = $recording_id and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to  and rpm < current_max_rpm and gear = 7  and gas > 0.3",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Differential Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front Wheel Rotation difference - current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, 2*(wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to\n  )\n\n  SELECT time,  speed_kmh, gas, steer_angle, front_angular_diff, perc_front_angular_diff, yaw\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, 2*(wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to\n  )\n\n  SELECT time,  speed_kmh, gas, steer_angle, front_angular_diff, perc_front_angular_diff, yaw\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Rear Wheel Rotation difference - current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, gas, steer_angle, wheel_angular_speed_rl - wheel_angular_speed_rr AS angular_diff, 2*(wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to\n  )\n\n  SELECT time,  speed_kmh, gas, steer_angle, angular_diff, perc_angular_diff, yaw\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, gas, steer_angle, wheel_angular_speed_rl - wheel_angular_speed_rr AS angular_diff, 2*(wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to\n  )\n\n  SELECT time,  speed_kmh, gas, steer_angle, angular_diff, perc_angular_diff, yaw\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Wheel Speed Difference over throttle",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "queryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 10 and 50",
       "rawQueryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 10 and 50",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 50 and 100",
       "rawQueryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 50 and 100",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 100 and 200",
       "rawQueryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 100 and 200",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Wheel Speed Difference over brakes",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "queryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 10 and 50",
       "rawQueryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 10 and 50",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and abs(local_angular_vel_y) > 0.1 and brake>0 and  speed_kmh between 50 and 100",
       "rawQueryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and abs(local_angular_vel_y) > 0.1 and brake>0 and  speed_kmh between 50 and 100",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 100 and 200",
       "rawQueryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and abs(local_angular_vel_y) > 0.1 and speed_kmh between 100 and 200",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Yaw over wheel speed difference, acceleration",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "queryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (150) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100)  and speed_kmh between 10 and 50",
       "rawQueryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100)  and speed_kmh between 10 and 50",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (150) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100)  and speed_kmh between 50 and 100",
       "rawQueryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100)  and speed_kmh between 50 and 100",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (150) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100)  and speed_kmh between 100 and 200",
       "rawQueryText": "\n  SELECT speed_kmh, gas, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) >100) or (fz_rl+fz_rr) > 100)  and speed_kmh between 100 and 200",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "yaw over wheel speed difference, braking",
     "type": "xychart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "queryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200)  and speed_kmh between 10 and 50",
       "rawQueryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200)  and speed_kmh between 10 and 50",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and brake>0 and  speed_kmh between 50 and 100",
       "rawQueryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200) and brake>0 and  speed_kmh between 50 and 100",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (172) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200)  and speed_kmh between 100 and 200",
       "rawQueryText": "\n  SELECT speed_kmh, gas, brake, steer_angle, wheel_angular_speed_fl - wheel_angular_speed_fr AS front_angular_diff, (wheel_angular_speed_fl - wheel_angular_speed_fr)/(wheel_angular_speed_fl+wheel_angular_speed_fr) as perc_front_angular_diff, wheel_angular_speed_rl - wheel_angular_speed_rr AS rear_angular_diff, (wheel_angular_speed_rl - wheel_angular_speed_rr)/(wheel_angular_speed_rl+wheel_angular_speed_rr) as perc_rear_angular_diff, -local_angular_vel_y as yaw, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) and (((fz_fl+fz_fr) <-200) or (fz_rl+fz_rr) < -200)  and speed_kmh between 100 and 200",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Brakes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brake Bias - current slip",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000047392 - 1000000040108) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, gas, steer_angle, brake, slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr, ((slip_ratio_fl/slip_ratio_rl) + (slip_ratio_fr/slip_ratio_rr))/2-1 as slip_front_bias, (slip_ratio_fl/slip_ratio_rl) -1 as slip_left_bias, (slip_ratio_fr/slip_ratio_rr) -1 as slip_right_bias, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN (107) AND (1000000000 + p.time_offset) * 1000 BETWEEN 1000000040108 AND 1000000047392 and brake >0\n  )\n\n  SELECT time,  speed_kmh, brake, slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr, slip_front_bias, slip_left_bias, slip_right_bias\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, gas, steer_angle, brake, slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr, ((slip_ratio_fl/slip_ratio_rl) + (slip_ratio_fr/slip_ratio_rr))/2-1 as slip_front_bias, (slip_ratio_fl/slip_ratio_rl) -1 as slip_left_bias, (slip_ratio_fr/slip_ratio_rr) -1 as slip_right_bias, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to and brake >0\n  )\n\n  SELECT time,  speed_kmh, brake, slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr, slip_front_bias, slip_left_bias, slip_right_bias\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "SELECT * from physics limit 1",
       "rawQueryText": "SELECT * from physics limit 1",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Brake Bias - current force",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, \"abs\", gas, steer_angle, brake, fz_fl, fz_fr, fz_rl, fz_rr, (fz_fl+ fz_fr)/(fz_fl+fz_fr+fz_rl+fz_rr) as force_front_bias, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to and brake >0\n  )\n\n  SELECT time,  \"abs\", speed_kmh, brake, force_front_bias\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \ndata AS (\n  SELECT (1000000000 + p.time_offset) AS time, speed_kmh, \"abs\", gas, steer_angle, brake, fz_fl, fz_fr, fz_rl, fz_rr, (fz_fl+ fz_fr)/(fz_fl+fz_fr+fz_rl+fz_rr) as force_front_bias, ROW_NUMBER() OVER (ORDER BY p.time_offset) AS rn \n  FROM physics p WHERE p.recording_id IN ($recording_id) AND (1000000000 + p.time_offset) * 1000 BETWEEN $__from AND $__to and brake >0\n  )\n\n  SELECT time,  \"abs\", speed_kmh, brake, force_front_bias\n FROM data, step WHERE (data.rn - 1) % step.s = 0 \nORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "SELECT * from physics limit 1",
       "rawQueryText": "SELECT * from physics limit 1",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "wheel forces under braking",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS \r\n(SELECT (1000000000 + time_offset) AS time, speed_kmh,  g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, slip_ratio_fl as slip_fl, slip_ratio_fr as slip_fr, slip_ratio_rl as slip_rl, slip_ratio_rr as slip_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE brake > 0 and recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\nSELECT time, speed_kmh,  g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, slip_fl, slip_fr, slip_rl, slip_rr FROM \r\ndata, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS \r\n(SELECT (1000000000 + time_offset) AS time, speed_kmh,  g_force_x AS g_lateral, g_force_z AS g_longit, -\"fz_FL\" AS wheelForceFL, -\"fz_FR\" AS wheelForceFR, -\"fz_RL\" AS wheelForceRL, -fz_RR AS wheelForceRR, slip_ratio_fl as slip_fl, slip_ratio_fr as slip_fr, slip_ratio_rl as slip_rl, slip_ratio_rr as slip_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE brake > 0 and recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\nSELECT time, speed_kmh,  g_lateral, g_longit, wheelForceFL, wheelForceFR, wheelForceRL, wheelForceRR, slip_fl, slip_fr, slip_rl, slip_rr FROM \r\ndata, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Brake Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "kelvin" } },
     "targets": [
      {
       "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000122464 - 999999967584) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (109) AND (1000000000 + time_offset) * 1000 BETWEEN 999999967584 AND 1000000122464) \nSELECT time,  brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \nSELECT time,  brake_temp_FL ,brake_temp_FR ,brake_temp_RL ,brake_temp_RR FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  { "title": "Wheel data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Slip data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "queryText": "WITH \r\nstep AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \r\ndata AS (SELECT (1000000000 + time_offset) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fr, slip_angle_fl, slip_angle_rr, slip_angle_rl,slip_ratio_fr, slip_ratio_fl, slip_ratio_rr, slip_ratio_rl, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\n\r\nSELECT time, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fl, slip_angle_fr, slip_angle_rl, slip_angle_rr,slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr  FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH \r\nstep AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \r\ndata AS (SELECT (1000000000 + time_offset) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fr, slip_angle_fl, slip_angle_rr, slip_angle_rl,slip_ratio_fr, slip_ratio_fl, slip_ratio_rr, slip_ratio_rl, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\n\r\nSELECT time, wheel_slip_fl, wheel_slip_fr, wheel_slip_rl, wheel_slip_rr, slip_angle_fl, slip_angle_fr, slip_angle_rl, slip_angle_rr,slip_ratio_fl, slip_ratio_fr, slip_ratio_rl, slip_ratio_rr  FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Wheel data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "queryText": "WITH \r\nstep AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \r\ndata AS (SELECT (1000000000 + time_offset) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\n\r\nSELECT time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH \r\nstep AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), \r\ndata AS (SELECT (1000000000 + time_offset) AS time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) \r\n\r\nSELECT time, wheel_load_fl, wheel_load_fr, wheel_load_rl, wheel_load_rr, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Suspension", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Suspension data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * (1000000040620 - 1000000037006) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN (80) AND (1000000000 + time_offset) * 1000 BETWEEN 1000000037006 AND 1000000040620) SELECT time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (SELECT (1000000000 + time_offset) AS time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, suspension_travel_fl, suspension_travel_fr, suspension_travel_rl, suspension_travel_rr FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,my_fl, my_fr, my_rl, my_rr , steer_angle, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id = $recording_id and g_force_x > 0.0 and steer_angle < 0 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time,  my_fl+ my_fr - my_rl - my_rr as oversteer\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,my_fl, my_fr, my_rl, my_rr , steer_angle, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id = $recording_id and g_force_x > 0.0 and steer_angle < 0 AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time,  my_fl+ my_fr - my_rl - my_rr as oversteer\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,my_fl, my_fr, my_rl, my_rr , ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id IN ($recording_id) and g_force_x < -0.0 AND steer_angle > 0 and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time, -(my_fl+ my_fr - my_rl - my_rr) as oversteer\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS\n (SELECT (1000000000 + time_offset) AS time,my_fl, my_fr, my_rl, my_rr , ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n FROM physics WHERE recording_id IN ($recording_id) and g_force_x < -0.0 AND steer_angle > 0 and (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to)  SELECT time, -(my_fl+ my_fr - my_rl - my_rr) as oversteer\n FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Suspension data",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "queryText": "select recording_id, -wheel_load_fl as wheel_load, -suspension_travel_fl as suspension_travel from physics where recording_id = 79",
     "rawQueryText": "select recording_id, -wheel_load_fl as wheel_load, -suspension_travel_fl as suspension_travel from physics where recording_id = $recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select recording_id, -wheel_load_fr as wheel_load, suspension_travel_fr as suspension_travel from physics where recording_id = 79",
     "rawQueryText": "select recording_id, -wheel_load_fr as wheel_load, suspension_travel_fr as suspension_travel from physics where recording_id = $recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select recording_id, wheel_load_rr as wheel_load, suspension_travel_rr as suspension_travel from physics where recording_id = 79",
     "rawQueryText": "select recording_id, wheel_load_rr as wheel_load, suspension_travel_rr as suspension_travel from physics where recording_id = $recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "select recording_id, wheel_load_fl as wheel_load, -suspension_travel_fl as suspension_travel from physics where recording_id = 79",
     "rawQueryText": "select recording_id, wheel_load_fl as wheel_load, -suspension_travel_fl as suspension_travel from physics where recording_id = $recording_id",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Suspension speed",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "mm / s" } },
   "targets": [
    {
     "queryText": "select rate_fl, rate_fr, rate_rl, rate_rr from (SELECT\n    time_offset, g_force_x, g_force_y,  g_force_z,\n    \n    1000*(suspension_travel_fl - LAG(suspension_travel_fl) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_fl,\n       1000* (suspension_travel_fr - LAG(suspension_travel_fr) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_fr,\n        1000*(suspension_travel_rl - LAG(suspension_travel_rl) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_rl,\n        1000*(suspension_travel_rr - LAG(suspension_travel_rr) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_rr\nFROM physics\nwhere recording_id = 40 and speed_kmh > 10\nORDER BY recording_id and time_offset) where rate_fl between -300 and 300 aND rate_fr between -300 and 300 and rate_rl between -300 and 300 and rate_rr between -300 and 300",
     "rawQueryText": "select rate_fl, rate_fr, rate_rl, rate_rr from (SELECT\n    time_offset, g_force_x, g_force_y,  g_force_z,\n    \n    1000*(suspension_travel_fl - LAG(suspension_travel_fl) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_fl,\n       1000* (suspension_travel_fr - LAG(suspension_travel_fr) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_fr,\n        1000*(suspension_travel_rl - LAG(suspension_travel_rl) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_rl,\n        1000*(suspension_travel_rr - LAG(suspension_travel_rr) OVER (ORDER BY time_offset)) / \n        (time_offset - LAG(time_offset) OVER (ORDER BY time_offset)) AS rate_rr\nFROM physics\nwhere recording_id = $recording_id and speed_kmh > 10\nORDER BY recording_id and time_offset) where rate_fl between -300 and 300 aND rate_fr between -300 and 300 and rate_rl between -300 and 300 and rate_rr between -300 and 300",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Oversteer/understeer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "queryText": "SELECT (1000000000 + time_offset) AS time, gas, brake, my_fl+my_fr - my_rr - my_rl as my_total from physics where recording_id = 150 and g_force_x > 0 and steer_angle < 0",
     "rawQueryText": "SELECT (1000000000 + time_offset) AS time, gas, brake, my_fl+my_fr - my_rr - my_rl as my_total from physics where recording_id = $recording_id and g_force_x > 0 and steer_angle < 0",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT (1000000000 + time_offset) AS time, gas, brake, -(my_fl+my_fr - my_rr - my_rl) as my_total from physics where recording_id = 150 and g_force_x < 0 and steer_angle > 0",
     "rawQueryText": "SELECT (1000000000 + time_offset) AS time, gas, brake, -(my_fl+my_fr - my_rr - my_rl) as my_total from physics where recording_id = $recording_id and g_force_x < 0 and steer_angle > 0",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "queryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, tyre_contact_normal_fl_x, tyre_contact_normal_fl_y, tyre_contact_normal_fl_z, tyre_contact_heading_fl_x, tyre_contact_heading_fl_y, tyre_contact_heading_fl_z, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n  FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, tyre_contact_normal_fl_x, tyre_contact_normal_fl_y, tyre_contact_normal_fl_z, tyre_contact_heading_fl_x, tyre_contact_heading_fl_y, tyre_contact_heading_fl_z FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "rawQueryText": "WITH step AS (SELECT MAX(1, CAST(333.0 * ($__to - $__from) / 1000 / 5000 AS INTEGER)) AS s), data AS (\n  SELECT (1000000000 + time_offset) AS time, tyre_contact_normal_fl_x, tyre_contact_normal_fl_y, tyre_contact_normal_fl_z, tyre_contact_heading_fl_x, tyre_contact_heading_fl_y, tyre_contact_heading_fl_z, ROW_NUMBER() OVER (ORDER BY time_offset) AS rn \n  FROM physics WHERE recording_id IN ($recording_id) AND (1000000000 + time_offset) * 1000 BETWEEN $__from AND $__to) SELECT time, tyre_contact_normal_fl_x, tyre_contact_normal_fl_y, tyre_contact_normal_fl_z, tyre_contact_heading_fl_x, tyre_contact_heading_fl_y, tyre_contact_heading_fl_z FROM data, step WHERE (data.rn - 1) % step.s = 0 ORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}